name: 'Run runn'
description: 'GitHub Action for runn, a tool for collecting code coverage.'
branding:
  icon: 'octagon'
  color: 'gray-dark'
inputs:
  command:
    description: run or list
    required: true
    default: 'run'
  path_pattern:
    description: Path pattern
    required: true
  filter:
    description: Path pattern
    required: null
  debug:
    description: Filter runbooks to be executed
    required: false
    default: false
  fail-fast:
    description: Fail fast mode
    required: false
    default: false
  skip-test:
    description: Skip test mode
    required: false
    default: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/k1low/runn:v0.31.0'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.path_pattern }}
    - ${{ (inputs.debug == true && '--debug') || '' }}
    - ${{ (inputs.fail-fast == true && '--fail-fast') || '' }}
    - ${{ (inputs.skip-test == true && '--skip-test') || '' }}
  env:
    RUNN_RUN: ${{ inputs.filter }}