name: Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-execution:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin:latest
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v4

      - name: 'Option test'
        uses: ./
        with:
          command: run
          path_pattern: testdata/path/to/*.yml
          debug: true
          verbose: true
          fail-fast: true
          skip-test: false
          shuffle: true
          concurrent: true
          enable-run-exec-scope: true
          labels: "integration,integration-http"
        env:
          # Override parameters in scenario with environment variables
          # NOTE: Specify `172.17.0.1` when accessing services on the GitHub Actions host.
          HTTPBIN_END_POINT: http://172.17.0.1:8080/
      - name: 'Check input parameter test'
        id: fail-step
        uses: ./
        with:
          command: completion
          path_pattern: testdata/path/to/exec.yml
          debug: true
          verbose: true
          fail-fast: true
          skip-test: false
          shuffle: true
          concurrent: true
        continue-on-error: true
