name: Integration

on:
  push:

jobs:
  test-execution:
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin:latest
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v2

      # option test
      - uses: ./
        with:
          command: run
          path_pattern: testdata/path/to/*.yml
          debug: true
          fail-fast: true
          skip-test: false
        env:
          HTTPBIN_END_POINT: http://172.17.0.1:8080/
      # filter test
      - uses: ./
        with:
          command: run
          path_pattern: testdata/path/to/*.yml
          filter: httpbin_include
        env:
          RUNN_RUN: "httpbin_include"
          HTTPBIN_END_POINT: http://172.17.0.1:8080/
